using Content.Shared.ADT.Silicons.Borgs.RoboticsConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System.Numerics;

namespace Content.Client.ADT.Silicons.Borgs.RoboticsConsole;

[GenerateTypedNameReferences]
public sealed partial class ADTRoboticsConsoleWindow : DefaultWindow
{
    public event Action<NetEntity>? OnLockToggle;

    public ADTRoboticsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(RoboticsConsoleState state)
    {
        BorgListContainer.RemoveAllChildren();

        foreach (var borg in state.Borgs)
        {
            var row = BuildBorgRow(borg);
            BorgListContainer.AddChild(row);
        }
    }

    private BoxContainer BuildBorgRow(RoboticsConsoleBorgEntry borg)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 2),
            MinSize = new Vector2(0, 30),
        };

        var statusColor = borg.Status switch
        {
            "Active" => Color.LightGreen,
            "Locked" => Color.Orange,
            "Disabled" => Color.Red,
            "Rebooting" => Color.Purple,
            _ => Color.Gray
        };

        var hpColor = borg.HealthPercent switch
        {
            < 0.25f => Color.Red,
            < 0.5f => Color.Orange,
            _ => Color.LightGreen
        };

        var batteryColor = borg.BatteryPercent switch
        {
            < 0.1f => Color.Red,
            < 0.3f => Color.Orange,
            _ => Color.LightGreen
        };

        var radioText = borg.RadioEnabled ? "ON" : "OFF";
        var radioColor = borg.RadioEnabled ? Color.LightGreen : Color.Gray;

        var nameLabel = new Label
        {
            Text = borg.Name,
            MinSize = new Vector2(120, 0),
            HorizontalExpand = true,
            ClipText = true,
        };

        var statusLabel = new Label
        {
            Text = borg.Status,
            FontColorOverride = statusColor,
            MinSize = new Vector2(70, 0),
            HorizontalAlignment = HAlignment.Center,
        };

        var hpLabel = new Label
        {
            Text = $"HP: {(borg.HealthPercent * 100):F0}%",
            FontColorOverride = hpColor,
            MinSize = new Vector2(60, 0),
            HorizontalAlignment = HAlignment.Center,
        };

        var batteryLabel = new Label
        {
            Text = $"Bat: {(borg.BatteryPercent * 100):F0}%",
            FontColorOverride = batteryColor,
            MinSize = new Vector2(70, 0),
            HorizontalAlignment = HAlignment.Center,
        };

        var moduleLabel = new Label
        {
            Text = borg.ModuleName,
            MinSize = new Vector2(80, 0),
            ClipText = true,
            HorizontalExpand = true,
        };

        var lawLabel = new Label
        {
            Text = borg.LawSet,
            MinSize = new Vector2(70, 0),
            HorizontalAlignment = HAlignment.Center,
        };

        var radioLabel = new Label
        {
            Text = radioText,
            FontColorOverride = radioColor,
            MinSize = new Vector2(40, 0),
            HorizontalAlignment = HAlignment.Center,
        };

        var lockButton = new Button
        {
            Text = "Lock",
            MinSize = new Vector2(50, 24),
        };
        var capturedNetEntity = borg.NetEntity;
        lockButton.OnPressed += _ => OnLockToggle?.Invoke(capturedNetEntity);

        row.AddChild(nameLabel);
        row.AddChild(statusLabel);
        row.AddChild(hpLabel);
        row.AddChild(batteryLabel);
        row.AddChild(moduleLabel);
        row.AddChild(lawLabel);
        row.AddChild(radioLabel);
        row.AddChild(lockButton);

        return row;
    }
}
