using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Silicons.Borgs.Core.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Silicons.Borgs.Core.UI;

[GenerateTypedNameReferences]
public sealed partial class BorgSelfDiagnosisWindow : FancyWindow
{
    public BorgSelfDiagnosisWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateDiagnosis(EntityUid uid, IEntityManager entity)
    {
        UpdateBattery(uid, entity);
        UpdateLaws(uid, entity);
        UpdateParts(uid, entity);
        UpdateWires(uid, entity);
    }

    private void UpdateBattery(EntityUid uid, IEntityManager entity)
    {
        if (!entity.TryGetComponent(uid, out BorgBatteryComponent? battery))
        {
            BatteryLabel.Text = "Cell: N/A";
            return;
        }

        var percent = battery.MaxCharge > 0 ? battery.Charge / battery.MaxCharge * 100 : 0;
        BatteryLabel.Text = $"Cell: {battery.Charge:F0}/{battery.MaxCharge:F0} ({percent:F0}%)";

        BatteryLabel.FontColorOverride = percent < 15 ? Color.Red : percent < 50 ? Color.Orange : Color.LightGreen;
    }

    private void UpdateLaws(EntityUid uid, IEntityManager entity)
    {
        if (!entity.TryGetComponent(uid, out BorgLawComponent? law))
        {
            LawLabel.Text = "Laws: N/A";
            return;
        }

        LawLabel.Text = $"Laws: {law.LawSet}";
        LawLabel.FontColorOverride = law.ZerothLawOverride ? Color.Red : Color.LightGreen;
    }

    private void UpdateParts(EntityUid uid, IEntityManager entity)
    {
        PartsContainer.RemoveAllChildren();

        var partQuery = entity.EntityQueryEnumerator<BorgComponentPartComponent>();
        var hasParts = false;
        while (partQuery.MoveNext(out var partUid, out var part))
        {
            hasParts = true;
            if (!part.Installed)
            {
                AddPartLabel(part.PartType.ToString(), "MISSING", Color.Red);
                continue;
            }

            var totalDamage = part.BruteDamage + part.BurnDamage;
            var healthPercent = part.MaxDamage > 0
                ? (1f - totalDamage / part.MaxDamage) * 100
                : 100f;

            var color = part.Broken ? Color.Red
                : healthPercent < 25 ? Color.OrangeRed
                : healthPercent < 50 ? Color.Orange
                : healthPercent < 75 ? Color.Yellow
                : Color.LightGreen;

            var status = part.Broken ? "BROKEN" : $"{healthPercent:F0}%";
            AddPartLabel(part.PartType.ToString(), status, color);
        }

        if (!hasParts)
        {
            AddPartLabel("No components found", "", Color.Gray);
        }
    }

    private void AddPartLabel(string name, string status, Color color)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 1, 0, 1)
        };

        container.AddChild(new Label
        {
            Text = $"  {name}",
            HorizontalExpand = true,
            FontColorOverride = color
        });

        container.AddChild(new Label
        {
            Text = status,
            HorizontalAlignment = HAlignment.Right,
            FontColorOverride = color
        });

        PartsContainer.AddChild(container);
    }

    private void UpdateWires(EntityUid uid, IEntityManager entity)
    {
        WiresContainer.RemoveAllChildren();

        if (!entity.TryGetComponent(uid, out BorgWiresComponent? wires))
        {
            var label = new Label { Text = "  No wire data", FontColorOverride = Color.Gray };
            WiresContainer.AddChild(label);
            return;
        }

        foreach (var wire in wires.Wires)
        {
            var color = wire.IsCut ? Color.Red : Color.LightGreen;
            var status = wire.IsCut ? "CUT" : wire.IsMended ? "OK" : "BROKEN";

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1, 0, 1)
            };

            container.AddChild(new Label
            {
                Text = $"  {wire.Type}",
                HorizontalExpand = true,
                FontColorOverride = color
            });

            container.AddChild(new Label
            {
                Text = status,
                HorizontalAlignment = HAlignment.Right,
                FontColorOverride = color
            });

            WiresContainer.AddChild(container);
        }
    }
}
