using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.ADT.Silicons.Borgs.Core.UI;

[GenerateTypedNameReferences]
public sealed partial class BorgSlotControl : PanelContainer
{
    public int SlotIndex { get; set; }

    public BorgSlotControl()
    {
        RobustXamlLoader.Load(this);
    }

    public BorgSlotControl(int slotIndex) : this()
    {
        SlotIndex = slotIndex;
    }

    public void SetActive(bool active)
    {
        if (active)
            SlotPanel.ModulateSelfOverride = Color.Green;
        else
            SlotPanel.ModulateSelfOverride = Color.Gray;
    }

    public void SetItem(EntityUid? item, IEntityManager entManager)
    {
        if (item == null || !entManager.EntityExists(item.Value))
        {
            SlotSprite.Visible = false;
            return;
        }

        SlotSprite.SetEntity(item.Value);
        SlotSprite.Visible = true;
    }
}
