using Content.Client.ADT.Silicons.Borgs.Core.Systems;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Silicons.Borgs.Core;
using Content.Shared.ADT.Silicons.Borgs.Core.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System.Numerics;

namespace Content.Client.ADT.Silicons.Borgs.Core.UI;

[GenerateTypedNameReferences]
public sealed partial class BorgHudWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    private EntityUid? _borgEntity;
    private readonly BorgSystem _borgSystem;
    private readonly List<BorgSlotControl> _slotControls = new(3);

    public event Action<EntityUid>? OnPdaPressed;
    public event Action<EntityUid>? OnHeadlampPressed;
    public event Action<EntityUid>? OnThrustersPressed;
    public event Action<EntityUid>? OnSensorModePressed;
    public event Action<EntityUid>? OnRadioPressed;

    public BorgHudWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _borgSystem = _entity.System<BorgSystem>();

        Slot0.SlotIndex = 0;
        Slot1.SlotIndex = 1;
        Slot2.SlotIndex = 2;

        _slotControls.Add(Slot0);
        _slotControls.Add(Slot1);
        _slotControls.Add(Slot2);

        PdaButton.OnPressed += _ => { if (_borgEntity != null) OnPdaPressed?.Invoke(_borgEntity.Value); };
        HeadlampButton.OnPressed += _ => { if (_borgEntity != null) OnHeadlampPressed?.Invoke(_borgEntity.Value); };
        ThrustersButton.OnPressed += _ => { if (_borgEntity != null) OnThrustersPressed?.Invoke(_borgEntity.Value); };
        SensorModeButton.OnPressed += _ => { if (_borgEntity != null) OnSensorModePressed?.Invoke(_borgEntity.Value); };
        RadioButton.OnPressed += _ => { if (_borgEntity != null) OnRadioPressed?.Invoke(_borgEntity.Value); };
    }

    public void SetBorgEntity(EntityUid uid)
    {
        _borgEntity = uid;
        UpdateAll();
    }

    public EntityUid? GetBorgEntity()
    {
        return _borgEntity;
    }

    public void UpdateAll()
    {
        if (_borgEntity == null || !_entity.EntityExists(_borgEntity.Value))
            return;

        var uid = _borgEntity.Value;
        UpdateSlots(uid);
        UpdateBattery(uid);
        UpdateHealth(uid);
        UpdateStatus(uid);
        UpdateStorages(uid);
    }

    private void UpdateSlots(EntityUid uid)
    {
        if (!_entity.TryGetComponent(uid, out BorgSlotComponent? slots))
            return;

        for (int i = 0; i < 3; i++)
        {
            if (i >= _slotControls.Count)
                break;

            var isActive = i == slots.CurrentSlot;
            _slotControls[i].SetActive(isActive);

            var item = slots[i];
            _slotControls[i].SetItem(item != EntityUid.Invalid ? item : null, _entity);
        }
    }

    private void UpdateBattery(EntityUid uid)
    {
        if (!_entity.TryGetComponent(uid, out BorgBatteryComponent? battery))
            return;

        var percent = battery.MaxCharge > 0 ? battery.Charge / battery.MaxCharge : 0f;
        ChargeBar.Value = percent;
        ChargeLabel.Text = $"{battery.Charge:F0}/{battery.MaxCharge:F0} ({percent * 100:F0}%)";
    }

    private void UpdateHealth(EntityUid uid)
    {
        var totalDamage = 0f;
        var maxDamage = 0f;

        var query = _entity.EntityQueryEnumerator<BorgComponentPartComponent>();
        while (query.MoveNext(out var partUid, out var bp))
        {
            if (!_entity.EntityExists(partUid))
                continue;

            totalDamage += bp.BruteDamage + bp.BurnDamage;
            maxDamage += bp.MaxDamage;
        }

        if (maxDamage > 0)
        {
            var healthPercent = (1f - totalDamage / maxDamage) * 100f;
            HealthLabel.Text = $"HP: {healthPercent:F0}%";

            if (healthPercent < 25f)
                HealthLabel.FontColorOverride = Color.Red;
            else if (healthPercent < 50f)
                HealthLabel.FontColorOverride = Color.Orange;
            else
                HealthLabel.FontColorOverride = Color.LightGreen;
        }
        else
        {
            HealthLabel.Text = "HP: N/A";
        }
    }

    private void UpdateStatus(EntityUid uid)
    {
        if (!_entity.TryGetComponent(uid, out BorgComponent? borg))
            return;

        if (_entity.TryGetComponent(uid, out BorgRebootComponent? reboot) && reboot.IsRebooting)
        {
            StatusLabel.Text = "Rebooting...";
            StatusLabel.FontColorOverride = Color.Orange;
        }
        else if (!borg.IsActive)
        {
            StatusLabel.Text = "Disabled";
            StatusLabel.FontColorOverride = Color.Red;
        }
        else
        {
            StatusLabel.Text = borg.Locked ? "Locked" : "Active";
            StatusLabel.FontColorOverride = borg.Locked ? Color.Orange : Color.LightGreen;
        }

        if (!_entity.TryGetComponent(uid, out BorgLawComponent? law))
            return;

        LawLabel.Text = law.LawSet;

        if (!_entity.TryGetComponent(uid, out BorgSlotComponent? slots))
            return;

        var activeSlot = slots.CurrentSlot;
        if (activeSlot >= 0 && activeSlot < slots.Count)
        {
            var slotItem = slots[activeSlot];
            if (slotItem == EntityUid.Invalid || !_entity.EntityExists(slotItem))
            {
                ModuleNameLabel.Text = "Empty slot";
                return;
            }

            if (_entity.EntityExists(slotItem))
            {
                var name = _entity.GetComponent<MetaDataComponent>(slotItem).EntityName;
                ModuleNameLabel.Text = name;
                return;
            }
        }

        ModuleNameLabel.Text = "Empty slot";
    }

    private void UpdateStorages(EntityUid uid)
    {
        StoragesContainer.RemoveAllChildren();

        if (!_entity.TryGetComponent(uid, out BorgComponent? borg))
            return;

        if (borg.EnergyStorages.Count == 0)
        {
            StoragesHeader.Visible = false;
            return;
        }

        StoragesHeader.Visible = true;

        foreach (var storage in borg.EnergyStorages)
        {
            var percent = storage.MaxAmount > 0 ? storage.CurrentAmount / storage.MaxAmount : 0f;
            var color = percent < 0.25f ? Color.Red : percent < 0.5f ? Color.Orange : Color.LightGreen;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1)
            };

            var nameLabel = new Label
            {
                Text = storage.Name,
                MinSize = new Vector2(80, 0),
                HorizontalExpand = true
            };

            var amountLabel = new Label
            {
                Text = $"{storage.CurrentAmount:F0}/{storage.MaxAmount:F0}",
                FontColorOverride = color,
                HorizontalAlignment = HAlignment.Right,
                HorizontalExpand = true
            };

            row.AddChild(nameLabel);
            row.AddChild(amountLabel);
            StoragesContainer.AddChild(row);
        }
    }
}
